import React from "react";
import Head from "next/head";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";

export default function Album({
  imageIds,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Khuram.co</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          background:
            "linear-gradient(90deg, rgba(15,32,39,1) 0%, rgba(32,58,67,1) 35%, rgba(44,83,100,1) 100%)",
        }}
      >
        <span style={{ fontSize: "50px", color: "white" }}>heyo</span>
      </main>
    </>
  );
}

/* <video src={"/logo.mp4"} autoPlay loop style={{ width: '500px', height: '500px' }} /> */

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: { imageIds: [] },
  };
};
