import React, { useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";
import styled from "styled-components";
import { authorize, getImageUrls } from "../helpers/google-drive";
import { AppStyleLayout } from "../components/AppStyleLayout";

import Image from "next/image";
import {
  AnimatePresence,
  motion,
  useScroll,
  useIsPresent,
} from "framer-motion";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });

export default function Album({
  imageIds,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const items = [
    { imgPath: imageIds[3] },
    { imgPath: imageIds[4] },
    { imgPath: imageIds[5] },
    { imgPath: imageIds[0] },
    { imgPath: imageIds[1] },
    { imgPath: imageIds[2] },
  ];

  const router = useRouter();
  const isPresent = useIsPresent();

  useEffect(() => {
    isPresent && console.log("gallery is present!");
    !isPresent && console.log("gallery has been removed!");
  }, [isPresent]);
  return (
    <>
      <Head>
        <title>Khuram.co</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
          //   background:
          //     "linear-gradient(90deg, rgba(142,45,226,1) 25%, rgba(74,0,224,1) 75%)",
          background:
            "linear-gradient(90deg, rgba(15,32,39,1) 0%, rgba(32,58,67,1) 35%, rgba(44,83,100,1) 100%)",
        }}
      >
        {/* <AppStyleLayout />
        <Zoom /> */}

        {/* <motion.div
          style={{ width: "100vw", height: "100vh", backgroundColor: "white" }}
          initial="initialState"
          animate="animateState"
          exit="exitState"
          variants={{
            initialState: {
              //   opacity: 0,
              clipPath: "polygon(50% 100%, 50% 100%, 100% 100%, 0% 100%)",
            },
            animateState: {
              //   opacity: 1,
              transition: { duration: 2 },
              clipPath: "polygon(0 0, 100% 0, 100% 100%, 0% 100%)",
            },
            exitState: {
              //   opacity: 0,
              clipPath: "polygon(0 0, 100% 0, 50% 0, 50% 0)",
            },
          }}
          key={router.route}
        > */}
        <span style={{ fontSize: "50px", color: "white" }}>heyo</span>
        {/* </motion.div> */}
      </main>
    </>
  );
}

/* <video src={"/logo.mp4"} autoPlay loop style={{ width: '500px', height: '500px' }} /> */

export const getStaticProps: GetStaticProps = async (context) => {
  // check query param for which images to fetch i.e. tokyo

  // fetch images from google drive
  //   const imageIds = await authorize()
  //     .then(async (authClient) => await getImageUrls(authClient))
  //     .catch(console.error);

  return {
    props: { imageIds: [] },
  };
};

// clip-path: polygon(0 0, 100% 0, 100% 100%, 0% 100%); clip-path:
// polygon(0 100%, 100% 100%, 100% 100%, 0% 100%);
