import { useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";
import { authorize, getImageUrls } from "@/helpers/google-drive";
import { Carousel } from "@/components/Carousel";
import { motion, useIsPresent } from "framer-motion";
import { AppStyleLayout } from "@/components/AppStyleLayout";

import Image from "next/image";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

// const items = [
//   {
//     imgPath: "/dev-logo.png",
//     alt: "Dev stuff. Find out what I can do.",
//     colourScheme: "#44CBB2",
//   },
//   {
//     imgPath: "/playlists-logo.png",
//     alt: "Playlists. All the vibes.",
//     colourScheme: "#F4D502",
//   },
//   {
//     imgPath: "/photography-logo.png",
//     alt: "Lights. Camera. Action. Take a look through my lens.",
//     colourScheme: "#EFEFEF",
//   },
//   {
//     imgPath: "/cooking-logo.png",
//     alt: "K's Cuisine. Or a recipe for disaster.",
//     colourScheme: "#DC1A21",
//   },
//   {
//     imgPath: "/cooking-logo.png",
//     alt: "K's Cuisine. Or a recipe for disaster.",
//     colourScheme: "#DC1A21",
//   },
//   {
//     imgPath: "/dev-logo.png",
//     alt: "Dev stuff. Find out what I can do.",
//     colourScheme: "#44CBB2",
//   },
//   {
//     imgPath: "/playlists-logo.png",
//     alt: "Playlists. All the vibes.",
//     colourScheme: "#F4D502",
//   },
// ];

export default function Home({}: InferGetStaticPropsType<
  typeof getStaticProps
>) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Khuram.co</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          height: "100vh",
        }}
      >
        <AppStyleLayout />

        {/* <video src={"/logo.mp4"} autoPlay loop style={{ width: '500px', height: '500px' }} /> */}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {},
  };
};
