import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { InferGetStaticPropsType } from "next";
import styled from "styled-components";
import { authorize, getImageUrls } from "@/helpers/google-drive";
import { AppStyleLayout } from "@/components/AppStyleLayout";
import { Zoom } from "@/components/Zoom";
import { Carousel } from "@/components/Carousel";

// style={{backgroundImage: `url(https://drive.google.com/uc?export=view&id=${imageIds[0]})`, backgroundSize: '100%'}}

const inter = Inter({ subsets: ["latin"] });

const items = [
  {
    imgPath: "/dev-logo.png",
    alt: "Dev stuff. Find out what I can do.",
    colourScheme: "#44CBB2",
  },
  {
    imgPath: "/playlists-logo.png",
    alt: "Playlists. All the vibes.",
    colourScheme: "#F4D502",
  },
  {
    imgPath: "/photography-logo.png",
    alt: "Lights. Camera. Action. Take a look through my lens.",
    colourScheme: "#EFEFEF",
  },
  {
    imgPath: "/cooking-logo.png",
    alt: "K's Cuisine. Or a recipe for disaster.",
    colourScheme: "#DC1A21",
  },
];

export default function Home({
  imageIds,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Khuram.co</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,100&display=swap');
        </style> */}
      </Head>
      <main
        style={{
          height: "100vh",
          // background: "rgb(15,32,39)",
          background:
            "linear-gradient(90deg, rgba(15,32,39,1) 0%, rgba(32,58,67,1) 35%, rgba(44,83,100,1) 100%)",
        }}
      >
        {/* <AppStyleLayout />
        <Zoom /> */}
        <text className="heading">PLAY. EXPLORE. CREATE. INSPIRE.</text>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            height: "100%",
            justifyContent: "center",
            overflow: "hidden",
          }}
        >
          <Carousel items={items} />
        </div>

        {/* <video src={"/logo.mp4"} autoPlay loop style={{ width: '500px', height: '500px' }} /> */}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  // const imageIds = await authorize()
  //   .then(async (authClient) => await getImageUrls(authClient))
  //   .catch(console.error);
  return {
    props: { imageIds: [] },
  };
};
